export default {
	SELECT_MOVIE: 'SELECT_MOVIE',
	GET_DISCOVER_MOVIES: 'GET_DISCOVER_MOVIES',
	GET_TOP_MOVIES: 'GET_TOP_MOVIES',
	TOP: 'TOP',
	DISCOVER: 'DISCOVER',
	SEARCH: 'SEARCH',
	LISTE: 'LISTE',
	VU: 'VU',
	GET_SEARCH_MOVIES: 'GET_SEARCH_MOVIES',
	SET_CURRENT_MOVIE: 'SET_CURRENT_MOVIE',
	GET_CURRENT_MOVIE: 'GET_CURRENT_MOVIE',
	LOGIN: 'LOGIN',
	DECO: 'DECO',
	GET_WATCHLIST: 'GET_WATCHLIST',
	GET_WATCHED: 'GET_WATCHED',
	ALREADY_WATCHED: 'ALREADY_WATCHED'
}